### ISSUE TITLE
Occasional crashes when using decoy databases

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/proteoform-suite#315]
* ProteoformCommunity.relate_et() crashed with an accession not in the list it was generated from... but it didn't happen the second time I ran it.
* Fixed another regarding constructing TheoreticalProteoformGroups from decoy contaminants https://github.com/smith-chem-wisc/proteoform-suite/pull/312
* These are hard to reproduce because decoy databases are randomized

**Comment by lschaffer2** [comment]
Crash at line 30 of PtmCombos sometimes:
                List<ModificationWithMass> unique_mods = ptm_data.Values.SelectMany(m => m).OfType<ModificationWithMass>().Distinct().ToList();

**Comment by lschaffer2** [comment]
System.InvalidOperationException: Collection was modified. enumeration operation may not execute

**Comment by acesnik** [comment]
I'm not sure how either of those lists could be modified. unique_mods is made just outside the for loop. ptm_data is made once for each theoretical proteoform, unless this is with unlocalized PTMs somehow.

**Comment by acesnik** [comment]
![image](https://user-images.githubusercontent.com/16342951/28933492-daebf018-7842-11e7-9320-0e53467a2d8e.png)

**Comment by acesnik** [comment]
Same bug as you noted before, @lschaffer2

**Comment by acesnik** [comment]
I tried it again without any changes; no crash. Ugh.

**Comment by acesnik** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__92`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProteoformSuiteInternal.PtmCombos.get_combinations(IDictionary`2 ptm_data, Int32 num_ptms_needed, Dictionary`2 modification_ranks, Int32 added_ptm_penalization, Boolean limit_triples_and_greater) in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteInternal\PtmCombos.cs:line 30
   at ProteoformSuiteInternal.TheoreticalProteoformDatabase.EnterTheoreticalProteformFamily(String seq, ProteinWithGoTerms prot, String accession, List`1 theoretical_proteoforms, Int32 decoy_number, IEnumerable`1 variableModifications) in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteInternal\TheoreticalProteoformDatabase.cs:line 431
   at ProteoformSuiteInternal.TheoreticalProteoformDatabase.<>c__DisplayClass24_1.<process_decoys>b__1(ProteinWithGoTerms p) in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteInternal\TheoreticalProteoformDatabase.cs:line 397
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at ProteoformSuiteInternal.TheoreticalProteoformDatabase.<>c__DisplayClass24_0.<process_decoys>b__0(Int32 decoyNumber) in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteInternal\TheoreticalProteoformDatabase.cs:line 393
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at ProteoformSuiteInternal.TheoreticalProteoformDatabase.process_decoys(ProteinWithGoTerms[] expanded_proteins, IEnumerable`1 variableModifications) in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteInternal\TheoreticalProteoformDatabase.cs:line 384
   at ProteoformSuiteInternal.TheoreticalProteoformDatabase.get_theoretical_proteoforms(String current_directory) in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteInternal\TheoreticalProteoformDatabase.cs:line 107
   at ProteoformSuiteGUI.TheoreticalDatabase.RunTheGamut() in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteGUI\TheoreticalDatabase.cs:line 144
   at ProteoformSuiteGUI.ProteoformSweet.full_run() in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteGUI\ProteoformSweet.cs:line 310
   at ProteoformSuiteGUI.LoadDeconvolutionResults.btn_fullRun_Click(Object sender, EventArgs e) in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteGUI\LoadDeconvolutionResults.cs:line 316
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__92`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProteoformSuiteInternal.PtmCombos.get_combinations(IDictionary`2 ptm_data, Int32 num_ptms_needed, Dictionary`2 modification_ranks, Int32 added_ptm_penalization, Boolean limit_triples_and_greater) in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteInternal\PtmCombos.cs:line 30
   at ProteoformSuiteInternal.TheoreticalProteoformDatabase.EnterTheoreticalProteformFamily(String seq, ProteinWithGoTerms prot, String accession, List`1 theoretical_proteoforms, Int32 decoy_number, IEnumerable`1 variableModifications) in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteInternal\TheoreticalProteoformDatabase.cs:line 431
   at ProteoformSuiteInternal.TheoreticalProteoformDatabase.<>c__DisplayClass24_1.<process_decoys>b__1(ProteinWithGoTerms p) in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteInternal\TheoreticalProteoformDatabase.cs:line 397
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at ProteoformSuiteInternal.TheoreticalProteoformDatabase.<>c__DisplayClass24_0.<process_decoys>b__0(Int32 decoyNumber) in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteInternal\TheoreticalProteoformDatabase.cs:line 393
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
---> (Inner Exception #0) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__92`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProteoformSuiteInternal.PtmCombos.get_combinations(IDictionary`2 ptm_data, Int32 num_ptms_needed, Dictionary`2 modification_ranks, Int32 added_ptm_penalization, Boolean limit_triples_and_greater) in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteInternal\PtmCombos.cs:line 30
   at ProteoformSuiteInternal.TheoreticalProteoformDatabase.EnterTheoreticalProteformFamily(String seq, ProteinWithGoTerms prot, String accession, List`1 theoretical_proteoforms, Int32 decoy_number, IEnumerable`1 variableModifications) in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteInternal\TheoreticalProteoformDatabase.cs:line 431
   at ProteoformSuiteInternal.TheoreticalProteoformDatabase.<>c__DisplayClass24_1.<process_decoys>b__1(ProteinWithGoTerms p) in C:\Users\antho\Documents\GitHub\proteoform-suite\ProteoformSuiteInternal\TheoreticalProteoformDatabase.cs:line 397
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
<---

**Comment by acesnik** [comment]
Oh! This is because the modification dictionaries are being modified by adding in the variable modifications each time. We should instead make sure to populate a new list of modifications in each parallel iteration.

`Dictionary<int, List<Modification>> possibleLocalizedMods = new Dictionary<int, List<Modification>>(prot.OneBasedPossibleLocalizedModifications).ToDictionary(kv => kv.Key, kv => new List<Modification>(kv.Value));`

**Comment by acesnik** [comment]
Fixed in https://github.com/smith-chem-wisc/proteoform-suite/pull/433
